### PR TITLE
Support Redmine 3.0

### PR DESCRIPTION
**Pull request by lammel**
To support redmine 3.0 some adjustments had to be made. 
This pull requests summarizes these fixes.
Compatibility with older versions of redmine is not tested with this PR.

### CODE REVIEW

**Comment by jbeauvois** [comment]
tested with Redmine 3
>> OK

unzip to plugins / Rename as recurring_tasks

bundle install --without development recurring_tasks
rake redmine:plugins:migrate
rake redmine:plugins:migrate NAME=recurring_tasks RAILS_ENV=production

**Comment by lammel** [comment]
Any chance this gets merged for the next release?

**Comment by nutso** [comment]
I went ahead and merged the changes -- I botched my dev/test installation and haven't had a chance to fix it yet, so <strong>I was not able to validate the changes</strong>. They look good on screen, and definitely appreciate the contribution, so didn't want to hold it up any further.

**Comment by lammel** [comment]
Thanks. Probably a prerelease would make sense to get a wider audience and
especially feedback for the pre-3.0 redmine use case. I did not test a
redmine version below 3.0.

There still seems to be an issue with recurring tasks without a fixed
schedule, which do open immediately after closing instead of after the
specified time. But that probably has nothing to do with my changes.

**Pull request merged**
